"""ATT&CK Navigator layer generation from Diamond Model output."""

CONFIDENCE_COLORS = {
    "high": "#ff6666",
    "medium": "#ffaa66",
    "low": "#ffff66",
}

CONFIDENCE_SCORES = {
    "high": 85,
    "medium": 50,
    "low": 25,
}


def confidence_to_color(confidence: str) -> str:
    return CONFIDENCE_COLORS.get(confidence.lower(), "#ffff66")


def technique_entry(
    technique_id: str,
    tactic: str,
    confidence: str,
    *,
    comment: str = "",
    source: str = "",
) -> dict:
    entry = {
        "techniqueID": technique_id,
        "tactic": tactic,
        "color": confidence_to_color(confidence),
        "score": CONFIDENCE_SCORES.get(confidence.lower(), 25),
        "enabled": True,
        "metadata": [
            {"name": "confidence", "value": confidence},
        ],
    }
    if comment:
        entry["comment"] = comment
    if source:
        entry["metadata"].append({"name": "source", "value": source})
    return entry


def build_attack_layer(
    name: str,
    description: str,
    techniques: list[dict],
    *,
    domain: str = "enterprise-attack",
) -> dict:
    return {
        "name": name,
        "versions": {"layer": "4.5", "attack": "15"},
        "domain": domain,
        "description": description,
        "filters": {"platforms": ["Windows", "Linux", "macOS"]},
        "sorting": 3,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffff66", "#ffaa66", "#ff6666"],
            "minValue": 0,
            "maxValue": 100,
        },
    }


def diamond_to_layer(diamond: dict, *, report_guid: str = "") -> dict:
    adversary_name = diamond.get("adversary", {}).get("name", "Unknown")
    layer_name = f"{adversary_name} - JTIA Analysis"

    techniques = []
    for ap in diamond.get("capability", {}).get("attack_patterns", []):
        confidence = ap.get("confidence", "low")
        techniques.append(
            technique_entry(
                technique_id=ap["mitre_id"],
                tactic=ap.get("kill_chain_phase", ""),
                confidence=confidence,
                comment=ap.get("name", ""),
            )
        )

    description = "Auto-generated by JTIA from Diamond Model analysis"
    if report_guid:
        description += f" (report: {report_guid})"

    return build_attack_layer(
        name=layer_name,
        description=description,
        techniques=techniques,
    )
